---
title: 'Kongen i gult'
Subtitle: "Dansk oversættelse af udvalgte noveller fra Robert W. Chambers 'The King in Yellow' til dansk. \n"
subject: 'Not known'
author:
    - 'Robert W. Chambers'
keywords: 'ebooks, Chambers'
rights: 'http://creativecommons.org/licenses/by-sa/2.5/'
language: da-DK
cover-image: /home/dennis/www/ebook/htdocs/books/55/assets/scaled-kongen-i-gult.jpg
date: 1895
private: true
format-arguments:
    pdf: '-V documentclass=book --template=templates/my.latex -S --toc --chapters -V fontsize=12pt  -V lang=danish'
    epub: '-S --toc --toc-depth=1'
    mobi: ok
    html-chunked: '-s -S'
ignore-files:
    - README.md
tags:
    - 'the king in yellow'
    - chambers
lang: da
stylesheet: epub.css
publisher: 'http://gittobook.org'
...


